### PR TITLE
Sync with upstream

### PR DESCRIPTION
**Pull request by sazapp-spectra**
This is an attempt at syncing our fork with upstream - primarily to pull in my fix for `oneOf`, but also to pull in other fixes since March.

The files I had to manually merge were `~/src/openapi-generator-spectra/modules/openapi-generator/src/main/resources/go-server/controller-api.mustache` and  `~/src/openapi-generator-spectra/modules/openapi-generator/src/main/resources/go-server/model.mustache`; everything else (in the `samples` directory) was then regenerated via ye olde
```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 

Upstream changes I had to manually merge (because of conflicts in `controller-api.mustache`) were:
[fix imports with go generation](https://github.com/OpenAPITools/openapi-generator/pull/18514)
[add field name in parsing error messages](https://github.com/OpenAPITools/openapi-generator/pull/18533)
[Fix: missing quotes for string default value](https://github.com/OpenAPITools/openapi-generator/pull/18546)
[Fix: error handling and linting](https://github.com/OpenAPITools/openapi-generator/pull/18550)

# Testing
Built a jar off of this branch, committed it to the lumos repo in [this PR](https://github.com/SpectraLogic/lumos/pull/5717), and let the automation suite run against it.

Once this is in, I'll build a jar off of `master` and open a new `lumos` PR with that committed - the changes should look identical to the test PR, just with a jar not built off a random dev branch.

### CODE REVIEW

**Comment by icubbon** [comment]
Can you create a matching PR in Lumos with the generated JAR so that we can see what the deltas are for us?

You should be able to do something like `./runInDocker.sh mvn install` and that create the jar and put in somewhere in `~/.m2/....`.

**Comment by sazapp-spectra** [comment]
I can reopen [this one](https://github.com/SpectraLogic/lumos/pull/5717) - this is the one that ran the automation updates against the code generated by this jar. I only closed it because I didn't want a jar built off a non-`master` branch getting into Lumos

**Review by icubbon — APPROVED** [review]
Way too many changes here to review but I reviewed all generated files in the test PR in the Lumos repo and it looks good.

**Comment by gonzogomez** [comment]
> I can reopen [this one](https://github.com/SpectraLogic/lumos/pull/5717) - this is the one that ran the automation updates against the code generated by this jar. I only closed it because I didn't want a jar built off a non-`master` branch getting into Lumos

Do you mind reopening as a formal pr. I cannot seem to find the build that ran the whole pipeline.  There are so many generated changes wanted to make sure we can at least run sanity.

**Review by gonzogomez — APPROVED** [review]
Thanks for reopening that other pr with generated changes!!!

**Pull request merged**
